name: autombile
description: "Graduation project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  dio: ^5.8.0+1
  intro_screen_onboarding_flutter: ^1.0.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

  fonts:
  - family: Sakana
    fonts:
        - asset: assets/fonts/Sakana.ttf

