name: autombile
description: "Graduation project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  dio: ^5.8.0+1
  intro_screen_onboarding_flutter: ^1.0.0
  curved_navigation_bar: ^1.0.6
  animated_notch_bottom_bar: ^1.0.3
  flutter_svg: ^2.2.0
  file_picker: ^10.2.0
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  syncfusion_flutter_gauges: ^24.1.41



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

  fonts:
  - family: Sakana
    fonts:
        - asset: assets/fonts/Sakana.ttf

  - family: Digital7Italic
    fonts:
       - asset: "assets/fonts/digital-7 (italic).ttf"

